# Generated by Django 6.0.5 on 2026-05-18 05:01

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="other_num",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="IN"
            ),
        ),
    ]
