# Generated by Django 6.0.5 on 2026-05-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_project_address_project_other_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="Address",
            field=models.TextField(null=True),
        ),
    ]
