# Generated by Django 6.0.5 on 2026-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="profile_image",
            field=models.ImageField(default="default.png", upload_to="profile/"),
        ),
    ]
