# Generated by Django 6.0.5 on 2026-05-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_project_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="profile_image",
            field=models.ImageField(default="img_1.jpg", upload_to="profile/"),
        ),
    ]
