# Generated by Django 6.0.5 on 2026-05-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_project_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="profile_image",
            field=models.ImageField(default="default.png", upload_to="profile/"),
        ),
    ]
