# Generated by Django 6.0.5 on 2026-06-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_alter_project_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="Address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="Date_birth",
            new_name="date_birth",
        ),
    ]
